name: Lint Source
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Check For --no-actions Flag
        if: ${{ contains(github.event.commits.*.message, '--no-actions') }}
        run: exit 0
      - name: Check For --no-lint Flag
        if: ${{ contains(github.event.commits.*.message, '--no-lint') }}
        run: exit 0
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Run Linter
        run: deno lint