name: Update Example
on: [push]

jobs:
  update-example:
    runs-on: ubuntu-20.04
    steps:
      - name: Check For --no-actions Flag
        if: ${{ contains(github.event.commits[0].message, '--no-actions') }}
        run: exit 0
      - name: Check For --no-example Flag
        if: ${{ contains(github.event.commits[0].message, '--no-example') }}
        run: exit 0
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Update Example
        run: |
          deno run --allow-read --allow-write --allow-run ./.github/exampleUpdater.ts
      - name: Push Example Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}